name: flashcards
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_value: ^0.0.1
  device_frame_plus: ^1.2.2+1
  drift: ^2.21.0
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  uuid: ^4.5.1

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
